//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbclient> tbclient { get; set; }
        public virtual DbSet<tbcontentpage> tbcontentpage { get; set; }
        public virtual DbSet<tbfacility> tbfacility { get; set; }
        public virtual DbSet<tbhotel> tbhotel { get; set; }
        public virtual DbSet<tbphone> tbphone { get; set; }
        public virtual DbSet<tbpublicity> tbpublicity { get; set; }
        public virtual DbSet<tbreservation> tbreservation { get; set; }
        public virtual DbSet<tbroom> tbroom { get; set; }
        public virtual DbSet<tbtyperoom> tbtyperoom { get; set; }
    }
}
