//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcontentpage
    {
        public int id { get; set; }
        public string referentpage { get; set; }
        public string urlimage { get; set; }
        public string typeimage { get; set; }
        public string content { get; set; }
    }
}
