//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbreservation
    {
        public int id { get; set; }
        public int idroom { get; set; }
        public int idclient { get; set; }
        public decimal amount { get; set; }
        public System.DateTime arrivaldate { get; set; }
        public System.DateTime departuredate { get; set; }
    
        public virtual tbclient tbclient { get; set; }
        public virtual tbroom tbroom { get; set; }
    }
}
